Bump version + Small fix
echoromeo/hanobo pull request #38
Opened 2022-02-08 16:51 UTC by Odyno

- Updated to the latest version of the library pynobo
- Introduced the async management  
- Fixed the configuration functionality with explicit ip
- Slightly modified the documentation

2022-02-18 12:06 UTC, echoromeo commented
Hi @Odyno, thanks for contributing!
Sorry for the late response here, I saw there were 230 changed lines and procrastinated a bit. However, it turns out your small fix introduced ~200 formatting changes, so it is quite time consuming to review all of the not relevant changes. Can you please revert those? Or, split them into two different commits so we can review what matters separately?

2022-02-28 13:38 UTC, Odyno commented
Unfortunately, I have the automatic code formatter that indents when you exceed 100 characters per line. I'll try to check this but I think the only thing that has been formatted are the logs.

2022-02-28 14:02 UTC, Odyno commented
I think I reduced the formatting aspects... is it ok now?

2022-02-28 21:15 UTC, echoromeo requested changes
It looks great, I only have a some editorial suggestions, plus bumping the version :)

2022-02-28 21:15 UTC, echoromeo commented on README.md
> +
```suggestion
Basic example with discovery:

      # Nobø Energy Control
      climate: 
        - platform: nobo_hub
          host: 123 # You can use the 3 last digits if using discovery

Example with explicit ip:

      # Nobø Energy Control
      climate: 
        - platform: nobo_hub
          host: 102000054137 # The full serial number
          ip_address: 192.168.1.30 # the IP of Hub


All available options:

```

2022-02-28 21:15 UTC, echoromeo commented on custom_components/nobo_hub/climate.py
> +def clean_up(name):
clean_up is a bit too generic name
```suggestion
def replace_nbsp(name):
```

2022-02-28 21:15 UTC, echoromeo commented on custom_components/nobo_hub/climate.py
> +            "name": clean_up(self._nobo.hub_info['name']),
```suggestion
            "name": replace_nbsp(self._nobo.hub_info['name']),
```

2022-02-28 21:15 UTC, echoromeo commented on custom_components/nobo_hub/manifest.json
>      "version": "1.1.3",
```suggestion
    "version": "1.1.4",
```

2022-03-07 18:13 UTC, Odyno commented
done

2022-08-22 14:07 UTC, oyvindwe commented
Note: ConfigFlow is being implemented in https://github.com/home-assistant/core/pull/50913

2022-10-22 08:49 UTC, oyvindwe commented
Home Assistant 2022.10 was released with Nobø Ecohub as an official integration, and the new version of `pynobo`.

2022-10-23 11:45 UTC, echoromeo commented
@Odyno sorry about the bad handling of your PR. I should have either merged it or rejected it ages ago.
This repo is now outdated because of the awesome work oyvindwe did to get an official integration in HA.
I will get it removed from [HACS ](https://github.com/echoromeo/default/pull/1) and then update the readme before archiving the repo.

2022-10-23 11:45 UTC, closed without merging